"""Google Sheets sync — push categorized Monarch data to a personal Google Sheet.

Authenticates via Desktop OAuth (google-token.json / google-credentials.json).
No Meta infra dependency. Works standalone with personal Gmail OAuth.

Layout per month (5 columns: Date | Category | Name | Amount | spacer):
  Row 1:  Month header + Year
  Row 2:  Income =SUM(income rows)
  Row 3:  Expenses =SUM(expense rows)
  Row 4:  Investment =SUM(investment rows)
  Row 5:  Diff =Income - Expenses - Investment (should be ~0 if all money accounted for)
  Rows 6-305:   Expense transactions (fixed region, sorted by date)
  Row 306:      "--- Investments ---" separator
  Rows 307-326: Investment transactions (fixed region)
  Row 327:      "--- Income ---" separator
  Rows 328-352: Income transactions (fixed region)
  (The *_START / *_END constants below are the source of truth.)

Categories come from rules/category_hierarchy.yaml: each Category cell is
"<emoji> <subcategory>" (the subcategory's emoji, else its parent's), and each
section's dropdown lists the subcategories of the expense / investment / income
parents in YAML order. Exclude parents (Transfers) have no section.

Amounts:
  Expenses: positive = outflow, negative = refund (subtracts from total)
  Income: positive = inflow, negative = reversal
  Investments: positive = outflow, negative = reversal/refund

Transactions < $1 are filtered out.
"""

import os
from decimal import Decimal
from functools import lru_cache
from pathlib import Path
from typing import Optional

import gspread
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow

from .hierarchy import build_subcategory_emoji_map, get_subcategories_by_type, load_hierarchy
from .models import MonthlyReport, Transaction, TransactionType

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
]

# Credential locations. Resolved in this order so the repo stays portable
# (and publishable) while existing checkouts keep working untouched:
#   1. GOOGLE_CREDENTIALS_FILE / GOOGLE_TOKEN_FILE env vars (set by .env).
#      This is what nagelia-dev-setup's `install.sh cashew` writes.
#   2. <repo>/.secrets/ — the convention the installer places files under.
#   3. The legacy shared location one level above the repo.
# The token is not a secret to be synced; it is regenerated by the OAuth flow
# and written next to whichever credentials file we ended up using.
REPO_ROOT = Path(__file__).resolve().parent.parent.parent
LEGACY_CREDS_DIR = REPO_ROOT.parent  # ~/Downloads/claude-projects/


def _resolve_cred_path(env_var: str, filename: str) -> Path:
    override = os.environ.get(env_var)
    if override:
        return Path(override).expanduser()
    local = REPO_ROOT / ".secrets" / filename
    if local.exists():
        return local
    return LEGACY_CREDS_DIR / filename


CREDS_FILE = _resolve_cred_path("GOOGLE_CREDENTIALS_FILE", "google-credentials.json")
# Token defaults to sitting beside the credentials file it was minted from.
TOKEN_FILE = (
    Path(os.environ["GOOGLE_TOKEN_FILE"]).expanduser()
    if os.environ.get("GOOGLE_TOKEN_FILE")
    else CREDS_FILE.parent / "google-token.json"
)

MONTH_NAMES = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]

# Fixed row regions (1-indexed).
# Section order (top to bottom): Summary, Expenses, Investment, Income.
# Investment starts at row 171 (right under expenses) with 20 slots; Income
# follows directly below, so investment reads first and income is its own
# block below. If a month ever exceeds a section's capacity, sync raises
# instead of silently dropping transactions (see _fit_to_region).
SUMMARY_START = 1     # Row 1-5: header + summary
EXPENSE_START = 6     # Row 6-305: expenses (300 slots)
EXPENSE_END = 305
INVEST_LABEL = 306    # Row 306: separator — investments start here
INVEST_START = 307    # Row 307-326: investments (20 slots)
INVEST_END = 326
INCOME_LABEL = 327    # Row 327: separator
INCOME_START = 328    # Row 328-352: income (25 slots)
INCOME_END = 352
TOTAL_ROWS = 352

# Sheet sections that get a category dropdown, by hierarchy parent type.
# "exclude" parents (Transfers) never reach the sheet, so they get none.
DROPDOWN_TYPES = ("expense", "income", "investment")


@lru_cache(maxsize=1)
def _default_emoji_map() -> dict[str, str]:
    """Subcategory emoji from the real category_hierarchy.yaml, read once per process."""
    return build_subcategory_emoji_map()


def _emoji_category(category: str, emoji_map: Optional[dict[str, str]] = None) -> str:
    """Prepend the category's emoji for display ("🛒 Groceries").

    A name with no emoji (e.g. a Monarch category the rules pass through that
    isn't in the hierarchy) stays plain. emoji_map defaults to the real YAML's.
    """
    if emoji_map is None:
        emoji_map = _default_emoji_map()
    emoji = emoji_map.get(category, "")
    if emoji:
        return f"{emoji} {category}"
    return category


def dropdown_categories(
    hierarchy: Optional[dict] = None, emoji_map: Optional[dict[str, str]] = None
) -> dict[str, list[str]]:
    """Emoji-prefixed dropdown values per sheet section, from category_hierarchy.yaml.

    Returns {"expense": [...], "income": [...], "investment": [...]}, each in
    YAML order (parent order, then subcategory order). Exclude-type parents are
    left out. Both arguments default to the real hierarchy file.
    """
    if hierarchy is None:
        hierarchy = load_hierarchy()
    if emoji_map is None:
        emoji_map = build_subcategory_emoji_map(hierarchy)
    return {
        section: [_emoji_category(sub, emoji_map) for sub in get_subcategories_by_type(section, hierarchy)]
        for section in DROPDOWN_TYPES
    }


MIN_AMOUNT = Decimal("1.00")  # Filter out transactions < $1


def _authenticate() -> gspread.Client:
    """Authenticate with Google using Desktop OAuth flow."""
    creds = None

    if TOKEN_FILE.exists():
        creds = Credentials.from_authorized_user_file(str(TOKEN_FILE), SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not CREDS_FILE.exists():
                raise FileNotFoundError(
                    f"Google credentials not found at {CREDS_FILE}. "
                    "Either download a Desktop-app OAuth client from Google Cloud "
                    "Console, set GOOGLE_CREDENTIALS_FILE, or run "
                    "`./install.sh cashew` from nagelia-dev-setup."
                )
            flow = InstalledAppFlow.from_client_secrets_file(str(CREDS_FILE), SCOPES)
            creds = flow.run_local_server(port=8092, open_browser=False)

        TOKEN_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(TOKEN_FILE, "w") as f:
            f.write(creds.to_json())

    return gspread.authorize(creds)


def _month_col_offset(month_num: int) -> int:
    """Starting column index (0-based) for a month (1-12).

    Each month = 5 columns: Date | Category | Name | Amount | spacer
    """
    return (month_num - 1) * 5


def _col_letter(col_idx: int) -> str:
    """Convert 0-based column index to A1 notation letter(s)."""
    result = ""
    idx = col_idx
    while True:
        result = chr(ord("A") + idx % 26) + result
        idx = idx // 26 - 1
        if idx < 0:
            break
    return result


def _ensure_tab(spreadsheet: gspread.Spreadsheet, tab_name: str) -> gspread.Worksheet:
    """Get or create a worksheet tab."""
    try:
        return spreadsheet.worksheet(tab_name)
    except gspread.WorksheetNotFound:
        return spreadsheet.add_worksheet(title=tab_name, rows=TOTAL_ROWS, cols=62)


def _txn_name(txn: Transaction) -> str:
    """Get the raw bank statement name (plaidName). Falls back to merchant.

    Prefixes with apostrophe if the name starts with +, =, -, or @
    to prevent Google Sheets from interpreting it as a formula.
    """
    name = txn.plaid_name or txn.merchant
    if name and name[0] in ("+", "=", "-", "@"):
        return "'" + name
    return name


def _filter_small(txns: list[Transaction]) -> list[Transaction]:
    """Remove transactions with abs(amount) < $1."""
    return [t for t in txns if abs(t.amount) >= MIN_AMOUNT]


def _txn_to_row(txn: Transaction, is_expense: bool = True) -> list[str]:
    """Convert a transaction to a sheet row [Date, Category, Name, Amount]."""
    amt = float(txn.amount)
    if is_expense or txn.resolved_type == TransactionType.INVESTMENT:
        # Negative in Monarch = outflow → positive in sheet
        # Positive in Monarch = refund → negative in sheet (subtracts from SUM)
        display_amt = abs(amt) if amt < 0 else -amt
    else:
        # Income: positive stays positive, negative stays negative
        display_amt = amt
    return [
        str(txn.date),
        _emoji_category(txn.resolved_category or txn.category),
        _txn_name(txn),
        f"{display_amt:.2f}",
    ]


class SectionOverflowError(Exception):
    """Raised when a month has more transactions than a section can hold.

    Guards against silently dropping transactions (which corrupts the
    monthly SUM totals). The fix is to grow the section's row region.
    """


def _fit_to_region(rows: list[list[str]], capacity: int, section: str, month: str) -> list[list[str]]:
    """Pad `rows` with blanks to exactly `capacity`, or raise if too many.

    NEVER silently truncates — dropping transactions produces wrong totals.
    """
    if len(rows) > capacity:
        raise SectionOverflowError(
            f"{month}: {len(rows)} {section} transactions exceed the "
            f"{capacity}-row section. Increase the {section} region in "
            f"sheets.py (EXPENSE/INCOME/INVEST_START/END) and re-sync."
        )
    padded = list(rows)
    while len(padded) < capacity:
        padded.append(["", "", "", ""])
    return padded


def _build_month_cells(
    report: MonthlyReport,
    transactions: list[Transaction],
    col_start: int,
) -> list[tuple[str, list[list[str]]]]:
    """Build cell updates for one month in fixed-row layout.

    Returns list of (range_a1, values) tuples for batch writing.
    """
    month_num = int(report.month.split("-")[1])
    year = report.month.split("-")[0]
    month_name = MONTH_NAMES[month_num - 1]
    amt_col = _col_letter(col_start + 3)
    col_a = _col_letter(col_start)
    col_d = _col_letter(col_start + 3)

    updates = []

    # --- Summary rows 1-5 ---
    summary = [
        [month_name, "", "", year],
        ["Income", "", "", f"=SUM({amt_col}{INCOME_START}:{amt_col}{INCOME_END})"],
        ["Expenses", "", "", f"=SUM({amt_col}{EXPENSE_START}:{amt_col}{EXPENSE_END})"],
        ["Investment", "", "", f"=SUM({amt_col}{INVEST_START}:{amt_col}{INVEST_END})"],
        ["Diff", "", "", f"={amt_col}2-{amt_col}3-{amt_col}4"],
    ]
    updates.append((f"{col_a}1:{col_d}5", summary))

    # --- Expense transactions (rows 6-170) ---
    expense_txns = _filter_small(sorted(
        [t for t in transactions if t.resolved_type == TransactionType.EXPENSE],
        key=lambda t: t.date,
    ))
    exp_rows = [_txn_to_row(t, is_expense=True) for t in expense_txns]
    exp_rows = _fit_to_region(
        exp_rows, EXPENSE_END - EXPENSE_START + 1, "expense", report.month
    )
    updates.append((f"{col_a}{EXPENSE_START}:{col_d}{EXPENSE_END}", exp_rows))

    # --- Income separator + transactions (rows 171-185) ---
    income_txns = _filter_small(sorted(
        [t for t in transactions if t.resolved_type == TransactionType.INCOME],
        key=lambda t: t.date,
    ))
    separator_and_income = [["", "--- Income ---", "", f"=SUM({amt_col}{INCOME_START}:{amt_col}{INCOME_END})"]]
    updates.append((f"{col_a}{INCOME_LABEL}:{col_d}{INCOME_LABEL}", separator_and_income))

    inc_rows = [_txn_to_row(t, is_expense=False) for t in income_txns]
    inc_rows = _fit_to_region(
        inc_rows, INCOME_END - INCOME_START + 1, "income", report.month
    )
    updates.append((f"{col_a}{INCOME_START}:{col_d}{INCOME_END}", inc_rows))

    # --- Investment separator + transactions (rows 186-200) ---
    invest_txns = _filter_small(sorted(
        [t for t in transactions if t.resolved_type == TransactionType.INVESTMENT],
        key=lambda t: t.date,
    ))
    separator_and_invest = [["", "--- Investments ---", "", f"=SUM({amt_col}{INVEST_START}:{amt_col}{INVEST_END})"]]
    updates.append((f"{col_a}{INVEST_LABEL}:{col_d}{INVEST_LABEL}", separator_and_invest))

    # Investment outflows: use expense-style sign logic
    inv_rows = [_txn_to_row(t, is_expense=True) for t in invest_txns]
    inv_rows = _fit_to_region(
        inv_rows, INVEST_END - INVEST_START + 1, "investment", report.month
    )
    updates.append((f"{col_a}{INVEST_START}:{col_d}{INVEST_END}", inv_rows))

    return updates


def sync_to_sheet(
    reports: list[tuple[MonthlyReport, list[Transaction]]],
    spreadsheet_id: str,
    tab_name: str = "FY-26-Auto",
) -> str:
    """Sync multiple months to the Google Sheet with fixed-row layout."""
    _default_emoji_map()  # read the category YAML now: a bad file fails before ws.clear()
    gc = _authenticate()
    spreadsheet = gc.open_by_key(spreadsheet_id)
    ws = _ensure_tab(spreadsheet, tab_name)

    # Ensure worksheet is big enough
    max_month = max(int(r.month.split("-")[1]) for r, _ in reports)
    needed_cols = max_month * 5
    if ws.row_count < TOTAL_ROWS:
        ws.resize(rows=TOTAL_ROWS)
    if ws.col_count < needed_cols:
        ws.resize(cols=needed_cols)

    # Clear the entire sheet first
    ws.clear()

    # Write each month's data
    for report, transactions in reports:
        month_num = int(report.month.split("-")[1])
        col_start = _month_col_offset(month_num)
        cell_updates = _build_month_cells(report, transactions, col_start)

        for cell_range, values in cell_updates:
            ws.update(cell_range, values, value_input_option="USER_ENTERED")

    return f"https://docs.google.com/spreadsheets/d/{spreadsheet_id}"


def format_sheet(
    spreadsheet_id: str,
    tab_name: str = "FY-26-Auto",
    num_months: int = 6,
) -> None:
    """Apply formatting: bold headers, yellow summary, column widths, dropdowns."""
    gc = _authenticate()
    spreadsheet = gc.open_by_key(spreadsheet_id)
    ws = spreadsheet.worksheet(tab_name)
    sheet_id = ws.id

    requests = []
    dropdowns = dropdown_categories()

    for month_idx in range(num_months):
        col_start = month_idx * 5

        # Bold + yellow background for row 1 (month header)
        requests.append({
            "repeatCell": {
                "range": {
                    "sheetId": sheet_id,
                    "startRowIndex": 0,
                    "endRowIndex": 1,
                    "startColumnIndex": col_start,
                    "endColumnIndex": col_start + 4,
                },
                "cell": {
                    "userEnteredFormat": {
                        "backgroundColor": {"red": 1, "green": 1, "blue": 0},
                        "textFormat": {"bold": True, "fontSize": 11},
                    }
                },
                "fields": "userEnteredFormat(backgroundColor,textFormat)",
            }
        })

        # Bold for summary rows 2-5 (Income, Expenses, Investment, Diff)
        requests.append({
            "repeatCell": {
                "range": {
                    "sheetId": sheet_id,
                    "startRowIndex": 1,
                    "endRowIndex": 5,
                    "startColumnIndex": col_start,
                    "endColumnIndex": col_start + 4,
                },
                "cell": {
                    "userEnteredFormat": {
                        "textFormat": {"bold": True},
                    }
                },
                "fields": "userEnteredFormat(textFormat)",
            }
        })

        # Yellow background for Diff row (row 5)
        requests.append({
            "repeatCell": {
                "range": {
                    "sheetId": sheet_id,
                    "startRowIndex": 4,
                    "endRowIndex": 5,
                    "startColumnIndex": col_start,
                    "endColumnIndex": col_start + 4,
                },
                "cell": {
                    "userEnteredFormat": {
                        "backgroundColor": {"red": 1, "green": 1, "blue": 0},
                        "textFormat": {"bold": True},
                    }
                },
                "fields": "userEnteredFormat(backgroundColor,textFormat)",
            }
        })

        # Bold + background for separator rows (Income label=171, Investment label=186)
        for sep_row_0idx in [INCOME_LABEL - 1, INVEST_LABEL - 1]:
            requests.append({
                "repeatCell": {
                    "range": {
                        "sheetId": sheet_id,
                        "startRowIndex": sep_row_0idx,
                        "endRowIndex": sep_row_0idx + 1,
                        "startColumnIndex": col_start,
                        "endColumnIndex": col_start + 4,
                    },
                    "cell": {
                        "userEnteredFormat": {
                            "backgroundColor": {"red": 0.85, "green": 0.92, "blue": 1},
                            "textFormat": {"bold": True, "italic": True},
                        }
                    },
                    "fields": "userEnteredFormat(backgroundColor,textFormat)",
                }
            })

        # Number format for Amount column (minus sign for negatives)
        requests.append({
            "repeatCell": {
                "range": {
                    "sheetId": sheet_id,
                    "startRowIndex": 1,
                    "endRowIndex": TOTAL_ROWS,
                    "startColumnIndex": col_start + 3,
                    "endColumnIndex": col_start + 4,
                },
                "cell": {
                    "userEnteredFormat": {
                        "numberFormat": {
                            "type": "NUMBER",
                            "pattern": "#,##0.00;-#,##0.00",
                        },
                    }
                },
                "fields": "userEnteredFormat(numberFormat)",
            }
        })

        # Column widths: Date=90, Category=130, Name=220, Amount=90, Spacer=20
        for i, width in enumerate([90, 130, 220, 90, 20]):
            requests.append({
                "updateDimensionProperties": {
                    "range": {
                        "sheetId": sheet_id,
                        "dimension": "COLUMNS",
                        "startIndex": col_start + i,
                        "endIndex": col_start + i + 1,
                    },
                    "properties": {"pixelSize": width},
                    "fields": "pixelSize",
                }
            })

        # Category dropdowns — section-specific lists
        # Expenses get expense categories, income gets income, investments get investment
        for start_row, end_row, cat_list in [
            (EXPENSE_START - 1, EXPENSE_END, dropdowns["expense"]),
            (INCOME_START - 1, INCOME_END, dropdowns["income"]),
            (INVEST_START - 1, INVEST_END, dropdowns["investment"]),
        ]:
            requests.append({
                "setDataValidation": {
                    "range": {
                        "sheetId": sheet_id,
                        "startRowIndex": start_row,
                        "endRowIndex": end_row,
                        "startColumnIndex": col_start + 1,
                        "endColumnIndex": col_start + 2,
                    },
                    "rule": {
                        "condition": {
                            "type": "ONE_OF_LIST",
                            "values": [
                                {"userEnteredValue": cat}
                                for cat in cat_list
                            ],
                        },
                        "showCustomUi": True,
                        "strict": False,  # Allow custom values too
                    },
                }
            })

    # Freeze first row and first 5 rows (summary)
    requests.append({
        "updateSheetProperties": {
            "properties": {
                "sheetId": sheet_id,
                "gridProperties": {"frozenRowCount": 5},
            },
            "fields": "gridProperties.frozenRowCount",
        }
    })

    if requests:
        spreadsheet.batch_update({"requests": requests})
